version: '3.7'

networks:
  private:
    external:
      name: private

services:
  salamanca-db:
    image: mysql:latest
    container_name: salamanca-db
    networks:
      - private
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
    restart: unless-stopped
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  # auth-service:
  #   image: spring-boot
  #   build:
  #     context: ./salamanca-cartelos.auth-service/
  #     dockerfile: Dockerfile
  #   container_name: salamanca-auth-service
  #   networks:
  #     - private
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   expose:
  #     - 8080
  #   volumes:
  #     - ./salamanca-cartelos.auth-service/:/usr/src/mymaven
  #     - ./salamanca-cartelos.auth-service/.m2:/root/.m2

  # proposals-service:
  #   build: ./salamanca-cartelos.proposals-service/
  #   container_name: salamanca-proposals-service
  #   command: bash -c "mvn spring-boot:run"
  #   depends_on:
  #     - salamanca-db
  #     - auth-service
  #   networks:
  #     - private
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  #   expose:
  #     - 8081